name: Build MSIX Installer

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # This allows you to trigger the build manually from GitHub!

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Inject Google Drive JSON
      shell: pwsh
      env:
        GOOGLE_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      run: |
        $env:GOOGLE_JSON | Out-File -FilePath "service-account.json" -Encoding utf8

    - name: Decode & Inject PFX Certificate
      shell: pwsh
      env:
        CERT_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
      run: |
        $bytes = [Convert]::FromBase64String($env:CERT_BASE64)
        [IO.File]::WriteAllBytes("AnimeStreamer_TemporaryKey.pfx", $bytes)

    - name: Build and Package MSIX
      run: msbuild AnimeStreamer.csproj /p:Configuration=Release /p:Platform=x64 /p:UapAppxPackageBuildMode=SideloadOnly /p:AppxBundle=Never /p:AppxPackageSigningEnabled=true /p:PackageCertificateKeyFile="AnimeStreamer_TemporaryKey.pfx" /restore

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Phillips-Anime-Installer
        path: bin\x64\Release\net8.0-windows10.0.19041.0\win-x64\AppPackages\**\*.msix